version: 2.1

orbs:
  docker: circleci/docker@2.4
  k8s: circleci/kubernetes@1.3
  sb: hubci/strawberry@0.8

workflows:
  build-n-test-wf:
    jobs:
      - sb/build:
          version: "0.23.0"
          source: "src"
          html-proofer: false
          filters:
            branches:
              ignore: trunk
      - docker/publish:
          attach-at: "src"
          deploy: false
          registry: "ghcr.io"
          image: "ghcr.io/cloud-unpacked/www.cloudunpacked.com"
          lint-dockerfile: true
          remote-docker-version: "20.10.24"
          tag: "$CIRCLE_SHA1,<< pipeline.git.branch >>,<< pipeline.number >>"
          requires:
            - sb/build
          filters:
            branches:
              ignore: trunk
  build-n-deploy-wf:
    jobs:
      - sb/build:
          version: "0.23.0"
          source: "src"
          html-proofer: false
          filters:
            branches:
              only: trunk
      - docker/publish:
          attach-at: "src"
          registry: "ghcr.io"
          image: "ghcr.io/cloud-unpacked/www.cloudunpacked.com"
          remote-docker-version: "20.10.24"
          tag: "$CIRCLE_SHA1,<< pipeline.git.branch >>,<< pipeline.number >>"
          requires:
            - sb/build
          filters:
            branches:
              only: trunk
          context: docker-ctx
      - deploy:
          requires:
            - docker/publish
          filters:
            branches:
              only: trunk
          context: k8s-ctx

jobs:
  deploy:
    docker:
      - image: hubci/strawberry:0.23.0
    steps:
      - k8s/install-kubeconfig
      - k8s/install-kubectl:
          kubectl-version: "v1.27.6"
      - run:
          name: "Deploy"
          command: kubectl set image --namespace=cloud-unpacked deployment/website website=ghcr.io/cloud-unpacked/www.cloudunpacked.com:$CIRCLE_SHA1
