apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloud-unpacked
  name: website-prod
  labels:
    app: website-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-prod
  template:
    metadata:
      labels:
        app: website-prod
    spec:
      containers:
      - name: website
        image: "ghcr.io/cloud-unpacked/www.cloudunpacked.com:latest"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: cloud-unpacked
  name: website-prod
  labels:
    app: website-prod
spec:
  type: ClusterIP
  selector:
    app: website-prod
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: cloud-unpacked
  name: website
  labels:
    app: website
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.cloudunpacked.com
    - cloudunpacked.com
    secretName: website-prod-tls
  rules:
  - host: www.cloudunpacked.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website
            port:
              number: 80
  - host: cloudunpacked.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website
            port:
              number: 80
